export const PEOPLE_GET_PENDING = "PEOPLE_GET_PENDING";
export const PEOPLE_GET_RESOLVED = "PEOPLE_GET_RESOLVED";
export const PEOPLE_GET_REJECTED = "PEOPLE_GET_REJECTED";

export const PROFILE_GET_PENDING = "PROFILE_GET_PENDING";
export const PROFILE_GET_RESOLVED = "PROFILE_GET_RESOLVED";
export const PROFILE_GET_REJECTED = "PROFILE_GET_REJECTED";
